"""
Customer Segmentation & Churn Analytics Suite
Author: Ayush Kumar
"""

import os
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(
    page_title="Customer Segmentation & Churn Intelligence",
    page_icon="👥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Dark UI Styling
st.markdown("""
<style>
    .stApp {
        background-color: #0b1120;
        color: #f8fafc;
    }
    div[data-testid="stMetric"] {
        background: #1e293b;
        border: 1px solid #334155;
        padding: 16px 20px;
        border-radius: 10px;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
    }
    div[data-testid="stMetricLabel"] {
        color: #94a3b8;
        font-size: 0.85rem;
        font-weight: 600;
        text-transform: uppercase;
    }
    div[data-testid="stMetricValue"] {
        color: #38bdf8;
        font-size: 1.8rem;
        font-weight: 700;
    }
    .metric-subtitle {
        color: #64748b;
        font-size: 0.75rem;
        margin-top: 4px;
    }
</style>
""", unsafe_allow_html=True)


@st.cache_data
def load_data():
    file_name = "customer_segments_enhanced.csv" if os.path.exists("customer_segments_enhanced.csv") else "customer_segments.csv"
    if not os.path.exists(file_name):
        return pd.DataFrame()

    df = pd.read_csv(file_name)
    df.columns = [c.strip() for c in df.columns]

    # Defensive fallbacks for Churn Risk if not yet generated by the ML pipeline
    if "Churn_Risk_Score" not in df.columns and "Recency" in df.columns and "Frequency" in df.columns:
        max_r = df["Recency"].max() if df["Recency"].max() > 0 else 1
        df["Churn_Risk_Score"] = np.round((0.65 * (df["Recency"] / max_r) + 0.35 * (1.0 / (1.0 + df["Frequency"]))) * 100, 2)

    return df


df = load_data()

# Sidebar Navigation
st.sidebar.title("Cohort Telemetry")
st.sidebar.markdown("**Enterprise RFM & Churn Modeling**")
st.sidebar.markdown("---")

if not df.empty and "Segment_Tier" in df.columns:
    tier_list = ["All"] + sorted(list(df["Segment_Tier"].dropna().unique()))
    selected_tier = st.sidebar.selectbox("Filter Segment Tier:", tier_list)
    if selected_tier != "All":
        df = df[df["Segment_Tier"] == selected_tier]

if not df.empty and "Country" in df.columns:
    country_list = ["All"] + sorted(list(df["Country"].dropna().unique()))
    selected_country = st.sidebar.selectbox("Filter Geography:", country_list)
    if selected_country != "All":
        df = df[df["Country"] == selected_country]

st.sidebar.markdown("---")
st.sidebar.markdown(
    """
    <div style="background-color: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 12px; margin-top: 10px;">
        <p style="margin: 0; font-size: 0.85rem; color: #94a3b8;">Designed by</p>
        <p style="margin: 0; font-size: 1.05rem; font-weight: 700; color: #38bdf8;">Ayush Kumar</p>
        <p style="margin: 4px 0 0 0; font-size: 0.75rem; color: #64748b;">Customer Segmentation Suite</p>
    </div>
    """,
    unsafe_allow_html=True
)

# Header
st.title("👥 Customer Segmentation & Churn Risk Analytics")
st.caption("Behavioral Cohort Intelligence, RFM Decomposition & Retention Modeling")

# Executive KPIs
total_customers = len(df)
total_spend = df["Monetary"].sum() if "Monetary" in df.columns else 0.0
avg_recency = df["Recency"].mean() if "Recency" in df.columns else 0.0
avg_frequency = df["Frequency"].mean() if "Frequency" in df.columns else 0.0

c1, c2, c3, c4 = st.columns(4)
with c1:
    st.metric("Total Customers", f"{total_customers:,}")
    st.markdown("<p class='metric-subtitle'>Analyzed Customer Cohort</p>", unsafe_allow_html=True)
with c2:
    st.metric("Cumulative Revenue", f"${total_spend:,.2f}")
    st.markdown("<p class='metric-subtitle'>Total Segment Monetary Spend</p>", unsafe_allow_html=True)
with c3:
    st.metric("Mean Recency", f"{avg_recency:.1f} days")
    st.markdown("<p class='metric-subtitle'>Days Since Last Transaction</p>", unsafe_allow_html=True)
with c4:
    st.metric("Mean Frequency", f"{avg_frequency:.1f} orders")
    st.markdown("<p class='metric-subtitle'>Lifetime Purchases per Customer</p>", unsafe_allow_html=True)

st.markdown("---")

# Visualizations Row 1: RFM Distribution & Segment Share
v1, v2 = st.columns([6, 4])

with v1:
    st.subheader("Monetary Spend vs. Recency (Days)")
    if "Recency" in df.columns and "Monetary" in df.columns:
        fig_scatter = px.scatter(
            df,
            x="Recency",
            y="Monetary",
            color="Segment" if "Segment" in df.columns else None,
            size="Frequency" if "Frequency" in df.columns else None,
            hover_data=["CustomerID"] if "CustomerID" in df.columns else None,
            template="plotly_dark",
            color_discrete_sequence=px.colors.qualitative.Bold,
            labels={"Recency": "Recency (Days Inactive)", "Monetary": "Total Spend ($)"}
        )
        fig_scatter.update_layout(paper_bgcolor="#1e293b", plot_bgcolor="#1e293b", margin=dict(t=30, b=30, l=20, r=20))
        st.plotly_chart(fig_scatter, use_container_width=True)

with v2:
    st.subheader("Customer Segment Share")
    if "Segment" in df.columns:
        seg_counts = df["Segment"].value_counts().reset_index()
        seg_counts.columns = ["Segment", "Count"]
        fig_pie = px.pie(
            seg_counts,
            names="Segment",
            values="Count",
            hole=0.55,
            template="plotly_dark",
            color_discrete_sequence=px.colors.qualitative.Prism
        )
        fig_pie.update_layout(paper_bgcolor="#1e293b", margin=dict(t=30, b=30, l=20, r=20))
        st.plotly_chart(fig_pie, use_container_width=True)

# Visualizations Row 2: Churn Risk & PCA Projections
v3, v4 = st.columns([5, 5])

with v3:
    st.subheader("Cohort Churn Risk Telemetry")
    if "Churn_Risk_Score" in df.columns:
        fig_hist = px.histogram(
            df,
            x="Churn_Risk_Score",
            nbins=30,
            color="Segment_Tier" if "Segment_Tier" in df.columns else None,
            template="plotly_dark",
            labels={"Churn_Risk_Score": "Calculated Churn Probability (%)"}
        )
        fig_hist.update_layout(paper_bgcolor="#1e293b", plot_bgcolor="#1e293b", margin=dict(t=30, b=30, l=20, r=20))
        st.plotly_chart(fig_hist, use_container_width=True)

with v4:
    st.subheader("2D PCA Feature Decomposition")
    if "PCA1" in df.columns and "PCA2" in df.columns:
        fig_pca = px.scatter(
            df,
            x="PCA1",
            y="PCA2",
            color="ML_Cluster_Persona" if "ML_Cluster_Persona" in df.columns else "Segment",
            template="plotly_dark",
            labels={"PCA1": "Principal Component 1", "PCA2": "Principal Component 2"}
        )
        fig_pca.update_layout(paper_bgcolor="#1e293b", plot_bgcolor="#1e293b", margin=dict(t=30, b=30, l=20, r=20))
        st.plotly_chart(fig_pca, use_container_width=True)
    elif "Frequency" in df.columns and "Monetary" in df.columns:
        fig_bubble = px.scatter(
            df,
            x="Frequency",
            y="Monetary",
            color="Segment" if "Segment" in df.columns else None,
            template="plotly_dark",
            log_y=True,
            labels={"Frequency": "Order Frequency", "Monetary": "Monetary Value (Log Scale)"}
        )
        fig_bubble.update_layout(paper_bgcolor="#1e293b", plot_bgcolor="#1e293b", margin=dict(t=30, b=30, l=20, r=20))
        st.plotly_chart(fig_bubble, use_container_width=True)

# Granular Explorer Table
st.markdown("---")
st.subheader("Granular Customer Segment Explorer")
st.dataframe(df.head(50), use_container_width=True)
